version: "3.8"
services:
  connectora:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:7.1.0
    ports:
      - 8081:8080 
    volumes:
      - ../config/connectorA/config.json:/config/config.json 
      - ../config/connectorA/connectora.local.p12:/conf/keystore.p12
      - ../data/cert/daps.local.p12:/config/truststore.p12
    environment:
      - CONFIGURATION_PATH=/config/config.json 
      - SERVER_SSL_ENABLED=false
      - DAPS_URL=http://217.72.203.88:13000
      - DAPS_TOKEN_URL=http://217.72.203.88:13000/token
      - DAPS_KEY_URL=http://217.72.203.88:13000/auth/jwks.json
      - DAPS_INCOMING_DAT_DEFAULT_WELLKNOWN=/auth/jwks.json
      
  connectorb:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:7.1.0 
    ports:    
      - 8082:8080  
    volumes:    
      - ../config/connectorB/config.json:/config/config.json 
      - ../config/connectorB/connectorb.local.p12:/conf/keystore.p12
      - ../data/cert/daps.local.p12:/config/truststore.p12
    environment:   
      - CONFIGURATION_PATH=/config/config.json  
      - SERVER_SSL_ENABLED=false
      - DAPS_URL=http://217.72.203.88:13000
      - DAPS_TOKEN_URL=http://217.72.203.88:13000/token
      - DAPS_KEY_URL=http://217.72.203.88:13000/auth/jwks.json
      - DAPS_INCOMING_DAT_DEFAULT_WELLKNOWN=/auth/jwks.json
                                
  dataspaceconnectorA-ui:    
    image: dataspaceconnector-ui 
    environment:  
      - CONNECTOR_URL=http://217.72.203.88:8081
      - CONNECTOR_USER=admin     
      - CONNECTOR_PASSWORD=password   
    ports: 
      - "8083:8083" 
                         
  dataspaceconnectorB-ui: 
    image: dataspaceconnector-ui  
    environment:    
      - CONNECTOR_URL=http://217.72.203.88:8082
      - CONNECTOR_USER=admin     
      - CONNECTOR_PASSWORD=password   
    ports:       
      - "8084:8083"
