version: "3.8"

services:
  broker:
    ports:
      - $TRUZZTPORT_BROKER_IDS_PORT:13003
      - $TRUZZTPORT_BROKER_MANAGEMENT_PORT:13004
      - $TRUZZTPORT_BROKER_DATA_PORT:13002
      - $TRUZZTPORT_BROKER_API_PORT:13001

  daps:
    ports:
      - $TRUZZTPORT_DAPS_PORT:4567

  tc-core:
    ports:
      - $TRUZZTPORT_CLEARING_PORT:9999

  connector:
    ports:
      - $TRUZZTPORT_CONNECTOR_IDS_PORT:13003
      - $TRUZZTPORT_CONNECTOR_MANAGEMENT_PORT:13004
      - $TRUZZTPORT_CONNECTOR_DATA_PORT:13002
      - $TRUZZTPORT_CONNECTOR_API_PORT:13001