version: "3.8"

services:
  proxy:
    image: nginx:1.21.6
    volumes:
      - ../config/proxy/nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - 13000:13000 # DAPS-Port
      - 13001:13001 # Broker-Port
      - 13002:13002 # Broker-Port
      - 13003:13003 # Broker-Port
      - 13004:13004 # Broker-Port
      - 13005:13005 # Clearing-house Port
      - 13101:13101 # Test-Connector 1
      - 13102:13102 # Test-Connector 1
      - 13103:13103 # Test-Connector 1
      - 13104:13104 # Test-Connector 1
      - 13201:13201 # Test-Connector 2
      - 13202:13202 # Test-Connector 2
      - 13203:13203 # Test-Connector 2
      - 13204:13204 # Test-Connector 2
    restart: always
    depends_on:
      broker:
        condition: service_started


  broker:
    image: federated-catalog
    # entrypoint:
      # -  "sh"
      # - "-c"
      # - "exec timeout -s INT 5m java -Djava.util.logging.config.file=/app/logging.properties -jar fc-in-memory.jar"
      # - "exec timeout -s INT 5m java -Djava.util.logging.config.file=/app/logging.properties -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar fc.jar"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    ports:
      - 5005:5005
    environment:
      WEB_HTTP_PORT: 13001
      WEB_HTTP_PATH: /api
      WEB_HTTP_DATA_PORT: 13002
      WEB_HTTP_DATA_PATH: /api/v1/data
      WEB_HTTP_IDS_PORT: 13003
      WEB_HTTP_IDS_PATH: /api/v1/ids
      WEB_HTTP_MANAGEMENT_PORT: 13004
      WEB_HTTP_MANAGEMENT_PATH: /
      EDC_IDS_ID: urn:connector:broker
      EDC_IDS_TITLE: 'truzzt IDS BaseCamp Broker'
      EDC_IDS_DESCRIPTION: "Truzzt's IDS BaseCamp Broker"
      EDC_IDS_ENDPOINT: http://$IP:13003/api/v1/ids
      IDS_WEBHOOK_ADDRESS: http://$IP:13003
      EDC_IDS_CURATOR: https://truzzt.com
      EDC_IDS_MAINTAINER: https://truzzt.com
      EDC_CONNECTOR_NAME: truzzt-example-connector
      EDC_HOSTNAME: broker
      EDC_API_AUTH_KEY: ApiKeyDefaultValue
      EDC_WEB_REST_CORS_ENABLED: 'true'
      EDC_WEB_REST_CORS_HEADERS: 'origin,content-type,accept,authorization,x-api-key'
      EDC_WEB_REST_CORS_ORIGINS: '*'
      EDC_FLYWAY_REPAIR: 'false'
      EDC_DATASOURCE_DEFAULT_URL: 'jdbc:postgresql://postgres:5432/broker'
      EDC_DATASOURCE_DEFAULT_USER: 'postgres'
      EDC_DATASOURCE_DEFAULT_PASSWORD: 'password'
      EDC_VAULT: /resources/vault/broker/vault.properties
      EDC_KEYSTORE: /resources/vault/broker/keystore.jks
      EDC_KEYSTORE_PASSWORD: password
      EDC_OAUTH_CERTIFICATE_ALIAS: 1
      EDC_OAUTH_PRIVATE_KEY_ALIAS: 1
      EDC_OAUTH_CLIENT_ID: $SKI_AKI
      EDC_OAUTH_TOKEN_URL: http://proxy:13000/token
      EDC_OAUTH_PROVIDER_JWKS_URL: http://proxy:13000/jwks.json
      EDC_OAUTH_PROVIDER_AUDIENCE: idsc:IDS_CONNECTORS_ALL

      EDC_CATALOG_CACHE_EXECUTION_DELAY_SECONDS: 10
      EDC_CATALOG_CACHE_EXECUTION_PERIOD_SECONDS: 10
      EDC_CATALOG_CACHE_PARTITION_NUM_CRAWLERS: 5
    volumes:
      - ./resources/vault/broker:/resources/vault/broker

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: broker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20
      start_period: 0s


  # broker-core:
  #   image: ghcr.io/truzzt/mds-broker-core:5.0.3
  #   environment:
  #     - SPARQL_ENDPOINT=http://fuseki:3030/connectorData
  #     - ELASTICSEARCH_HOSTNAME=elastic
  #     - SHACL_VALIDATION=true
  #     - DAPS_VALIDATE_INCOMING=false
  #     - IDENTITY_JAVAKEYSTORE=/etc/cert/keystore.jks
  #     - COMPONENT_URI=$BROKER_CORE_COMPONENT_URI
  #     - COMPONENT_CATALOGURI=$BROKER_CORE_COMPONENT_CATALOGURI
  #     - DAPS_URL=http://217.72.203.88:13000/token
  #   depends_on:
  #     - elastic
  #     - fuseki
  #   volumes:
  #     - ../data/cert/broker.local.jks:/etc/cert/keystore.jks

  # fuseki:
  #   image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker-open/fuseki
  #   volumes:
  #     - fuseki-data:/fuseki

  # elastic:
  #   image: elasticsearch:7.16.2
  #   environment:
  #     - http.port=9200
  #     - discovery.type=single-node
  #   volumes:      
  #     - elastic-data:/usr/share/elasticsearch/data

  # mongo:
  #   image: mongo:latest
  #   volumes:
  #     - mongo-data:/data/db

  # broker-backend:
  #   image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker/mongodb-handler:5.0.2-DF
  #   environment:
  #     - MONGODB_ENDPOINT=mongodb://mongo:27017/users
  #     - JWT_SECRET=$BROKER_BACKEND_JWT_SECRET
  #     - ADMIN_PASSWORD=$ADMIN_PASSWORD
  #     - BROKER_URL=http://broker-core:8080
  #   depends_on:
  #     - mongo
  
  # broker-frontend:
  #   image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker/frontend-mobids:5.0.2-DF
  #   environment:
  #     - REACT_APP_BROKER_URL=http://localhost:13002

  daps-core:
    image: ghcr.io/fraunhofer-aisec/omejdn-server:1.7.1
    environment:
      - OMEJDN_OPENID=true
      - OMEJDN_ACCEPT_AUDIENCE=idsc:IDS_CONNECTORS_ALL
      - OMEJDN_DEFAULT_AUDIENCE=idsc:IDS_CONNECTORS_ALL
      - OMEJDN_ADMIN=${DAPS_ADMIN_USERNAME}:${ADMIN_PASSWORD}
    volumes:
      - ../data/daps/clients.yml:/opt/config/clients.yml
      - ../config/daps:/opt/config
      - ../data/daps/clients/:/opt/keys/clients
      - ../data/cert/daps.local.key:/opt/keys/omejdn/omejdn.key

  test-connector-a:
    profiles:
      - test
    image: registry.orbiter.de/orbiter/mds-edc:${TAG:-dev}
    restart: always
    entrypoint:
      -  "sh"
      - "-c"
      # - "exec timeout -s INT 5m java -Djava.util.logging.config.file=/app/logging.properties -jar mds_edc.jar"
      - "exec timeout -s INT 5m java -Djava.util.logging.config.file=/app/logging.properties -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -jar mds_edc.jar"
    depends_on:
      postgres-a:
        condition: service_healthy
      broker:
        condition: service_started
    ports:
      - 5006:5006
    environment:
      WEB_HTTP_PORT: 13101
      WEB_HTTP_PATH: /api
      WEB_HTTP_IDS_PORT: 13103
      WEB_HTTP_IDS_PATH: /api/v1/ids
      WEB_HTTP_MANAGEMENT_PORT: 13104
      WEB_HTTP_MANAGEMENT_PATH: /api/v1/management
      EDC_IDS_ID: urn:connector:example-connector
      EDC_IDS_TITLE: 'truzzt Test EDC Connector'
      EDC_IDS_DESCRIPTION: 'Minimally configured Open Source EDC built by truzzt.'
      EDC_IDS_ENDPOINT: http://proxy:13103/api/v1/ids
      IDS_WEBHOOK_ADDRESS: http://proxy:13103
      EDC_IDS_CURATOR: https://truzzt.com
      EDC_IDS_MAINTAINER: https://truzzt.com
      EDC_CONNECTOR_NAME: truzzt-example-connector
      EDC_HOSTNAME: proxy:13103
      EDC_API_AUTH_KEY: ApiKeyDefaultValue
      EDC_WEB_REST_CORS_ENABLED: 'true'
      EDC_WEB_REST_CORS_HEADERS: 'origin,content-type,accept,authorization,x-api-key'
      EDC_WEB_REST_CORS_ORIGINS: '*'

      EDC_VAULT: /resources/vault/edc_a/vault.properties
      EDC_BROKER_BASE_URL: http://proxy:13004
      EDC_CLEARINGHOUSE_LOG_URL: http://proxy:13005/messages/log
      EDC_KEYSTORE: /resources/vault/edc_a/keystore.jks
      EDC_KEYSTORE_PASSWORD: password
      EDC_OAUTH_PUBLIC_KEY_ALIAS: 1
      EDC_OAUTH_PRIVATE_KEY_ALIAS: 1
      EDC_OAUTH_CLIENT_ID: $TEST_EDC_A_SKI_AKI
      EDC_OAUTH_TOKEN_URL: http://proxy:13000/token
      EDC_OAUTH_PROVIDER_JWKS_URL: http://proxy:13000/jwks.json
      EDC_OAUTH_PROVIDER_AUDIENCE: idsc:IDS_CONNECTORS_ALL

      # Flyway Extension
      EDC_DATASOURCE_ASSET_NAME: asset
      EDC_DATASOURCE_ASSET_URL: jdbc:postgresql://postgres-a:5432/edc1
      EDC_DATASOURCE_ASSET_USER: postgres
      EDC_DATASOURCE_ASSET_PASSWORD: password

      EDC_DATASOURCE_CONTRACTDEFINITION_NAME: contractdefinition
      EDC_DATASOURCE_CONTRACTDEFINITION_URL: jdbc:postgresql://postgres-a:5432/edc1
      EDC_DATASOURCE_CONTRACTDEFINITION_USER: postgres
      EDC_DATASOURCE_CONTRACTDEFINITION_PASSWORD: password

      EDC_DATASOURCE_CONTRACTNEGOTIATION_NAME: contractnegotiation
      EDC_DATASOURCE_CONTRACTNEGOTIATION_URL: jdbc:postgresql://postgres-a:5432/edc1
      EDC_DATASOURCE_CONTRACTNEGOTIATION_USER: postgres
      EDC_DATASOURCE_CONTRACTNEGOTIATION_PASSWORD: password

      EDC_DATASOURCE_POLICY_NAME: policy
      EDC_DATASOURCE_POLICY_URL: jdbc:postgresql://postgres-a:5432/edc1
      EDC_DATASOURCE_POLICY_USER: postgres
      EDC_DATASOURCE_POLICY_PASSWORD: password

      EDC_DATASOURCE_TRANSFERPROCESS_NAME: transferprocess
      EDC_DATASOURCE_TRANSFERPROCESS_URL: jdbc:postgresql://postgres-a:5432/edc1
      EDC_DATASOURCE_TRANSFERPROCESS_USER: postgres
      EDC_DATASOURCE_TRANSFERPROCESS_PASSWORD: password

      EDC_DATASOURCE_DATAPLANEINSTANCE_NAME: dataplaneinstance
      EDC_DATASOURCE_DATAPLANEINSTANCE_URL: jdbc:postgresql://postgres-a:5432/edc1
      EDC_DATASOURCE_DATAPLANEINSTANCE_USER: postgres
      EDC_DATASOURCE_DATAPLANEINSTANCE_PASSWORD: password
    
    volumes:
      - ./resources/vault/edc_a:/resources/vault/edc_a

  test-connector-b:
    profiles:
      - test
    image: registry.orbiter.de/orbiter/mds-edc:${TAG:-dev}
    restart: always
    entrypoint:
      -  "sh"
      - "-c"
      # - "exec timeout -s INT 5m java -Djava.util.logging.config.file=/app/logging.properties -jar mds_edc.jar"
      - "exec timeout -s INT 5m java -Djava.util.logging.config.file=/app/logging.properties -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007 -jar mds_edc.jar"
    depends_on:
      postgres-b:
        condition: service_healthy
      broker:
        condition: service_started
    ports:
      - 5007:5007
    environment:
      WEB_HTTP_PORT: 13201
      WEB_HTTP_PATH: /api
      WEB_HTTP_IDS_PORT: 13203
      WEB_HTTP_IDS_PATH: /api/v1/ids
      WEB_HTTP_MANAGEMENT_PORT: 13204
      WEB_HTTP_MANAGEMENT_PATH: /api/v1/management
      EDC_IDS_ID: urn:connector:example-connector
      EDC_IDS_TITLE: 'truzzt Test EDC Connector'
      EDC_IDS_DESCRIPTION: 'Minimally configured Open Source EDC built by truzzt.'
      EDC_IDS_ENDPOINT: http://proxy:13203/api/v1/ids
      IDS_WEBHOOK_ADDRESS: http://proxy:13203
      EDC_IDS_CURATOR: https://truzzt.com
      EDC_IDS_MAINTAINER: https://truzzt.com
      EDC_CONNECTOR_NAME: truzzt-example-connector
      EDC_HOSTNAME: proxy:13203
      EDC_API_AUTH_KEY: ApiKeyDefaultValue
      EDC_WEB_REST_CORS_ENABLED: 'true'
      EDC_WEB_REST_CORS_HEADERS: 'origin,content-type,accept,authorization,x-api-key'
      EDC_WEB_REST_CORS_ORIGINS: '*'

      EDC_VAULT: /resources/vault/edc_b/vault.properties
      EDC_BROKER_BASE_URL: http://proxy:13004
      EDC_CLEARINGHOUSE_LOG_URL: http://proxy:13005/messages/log
      EDC_KEYSTORE: /resources/vault/edc_b/keystore.jks
      EDC_KEYSTORE_PASSWORD: password
      EDC_OAUTH_PUBLIC_KEY_ALIAS: 1
      EDC_OAUTH_PRIVATE_KEY_ALIAS: 1
      EDC_OAUTH_CLIENT_ID: $TEST_EDC_B_SKI_AKI
      EDC_OAUTH_TOKEN_URL: http://proxy:13000/token
      EDC_OAUTH_PROVIDER_JWKS_URL: http://proxy:13000/jwks.json
      EDC_OAUTH_PROVIDER_AUDIENCE: idsc:IDS_CONNECTORS_ALL

      # Flyway Extension
      EDC_DATASOURCE_ASSET_NAME: asset
      EDC_DATASOURCE_ASSET_URL: jdbc:postgresql://postgres-b:5432/edc1
      EDC_DATASOURCE_ASSET_USER: postgres
      EDC_DATASOURCE_ASSET_PASSWORD: password

      EDC_DATASOURCE_CONTRACTDEFINITION_NAME: contractdefinition
      EDC_DATASOURCE_CONTRACTDEFINITION_URL: jdbc:postgresql://postgres-b:5432/edc1
      EDC_DATASOURCE_CONTRACTDEFINITION_USER: postgres
      EDC_DATASOURCE_CONTRACTDEFINITION_PASSWORD: password

      EDC_DATASOURCE_CONTRACTNEGOTIATION_NAME: contractnegotiation
      EDC_DATASOURCE_CONTRACTNEGOTIATION_URL: jdbc:postgresql://postgres-b:5432/edc1
      EDC_DATASOURCE_CONTRACTNEGOTIATION_USER: postgres
      EDC_DATASOURCE_CONTRACTNEGOTIATION_PASSWORD: password

      EDC_DATASOURCE_POLICY_NAME: policy
      EDC_DATASOURCE_POLICY_URL: jdbc:postgresql://postgres-b:5432/edc1
      EDC_DATASOURCE_POLICY_USER: postgres
      EDC_DATASOURCE_POLICY_PASSWORD: password

      EDC_DATASOURCE_TRANSFERPROCESS_NAME: transferprocess
      EDC_DATASOURCE_TRANSFERPROCESS_URL: jdbc:postgresql://postgres-b:5432/edc1
      EDC_DATASOURCE_TRANSFERPROCESS_USER: postgres
      EDC_DATASOURCE_TRANSFERPROCESS_PASSWORD: password

      EDC_DATASOURCE_DATAPLANEINSTANCE_NAME: dataplaneinstance
      EDC_DATASOURCE_DATAPLANEINSTANCE_URL: jdbc:postgresql://postgres-b:5432/edc1
      EDC_DATASOURCE_DATAPLANEINSTANCE_USER: postgres
      EDC_DATASOURCE_DATAPLANEINSTANCE_PASSWORD: password
    
    volumes:
      - ./resources/vault/edc_b:/resources/vault/edc_b

  postgres-a:
    profiles:
      - test
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edc1
    volumes:
      - postgres-a-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20
      start_period: 0s

  postgres-b:
    profiles:
      - test
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edc1
    volumes:
      - postgres-b-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20
      start_period: 0s


volumes:
  postgres-data:
  postgres-a-data:
  postgres-b-data:
  # mongo-data:
  # fuseki-data:
  # elastic-data:

