version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../data/${TRUZZTPORT_ENV_SLUG}/proxy:/certificates
    command:
      - --providers.docker=true
      - --entryPoints.web.address=:80
      - --providers.docker.exposedbydefault=false
      - --api.dashboard=true
      # - --log.level=DEBUG
      - --accesslog=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.demo.truzztport.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$sfMMH.Mj$$M3PtggBoBBG1cc8pGboD80

  daps:
    labels:
      - traefik.enable=true
      - traefik.http.routers.daps-http.rule=Host(`$TRUZZTPORT_DAPS_DOMAIN`)
      - traefik.http.services.daps.loadbalancer.server.port=4567   

  broker:
    labels:
      - traefik.enable=true
      # managment api
      - traefik.http.routers.broker-management-http.rule=Host(`$TRUZZTPORT_BROKER_DOMAIN`)
      - traefik.http.routers.broker-management-http.service=broker-management
      - traefik.http.services.broker-management.loadbalancer.server.port=13004

      # ids api
      - traefik.http.routers.broker-ids-http.rule=Host(`$TRUZZTPORT_BROKER_DOMAIN`) && PathPrefix(`/api/v1/ids`)
      - traefik.http.routers.broker-ids-http.service=broker-ids
      - traefik.http.services.broker-ids.loadbalancer.server.port=13003

      # data api
      - traefik.http.routers.broker-data-http.rule=Host(`$TRUZZTPORT_BROKER_DOMAIN`) && PathPrefix(`/api/v1/data`)
      - traefik.http.routers.broker-data-http.service=broker-data
      - traefik.http.services.broker-data.loadbalancer.server.port=13002

      # api
      - traefik.http.routers.broker-api-http.rule=Host(`$TRUZZTPORT_BROKER_DOMAIN`) && PathPrefix(`/api`)
      - traefik.http.routers.broker-api-http.service=broker-api
      - traefik.http.services.broker-api.loadbalancer.server.port=13001

  tc-core:
    labels:
      - traefik.enable=true
      - traefik.http.routers.clearing-http.rule=Host(`$TRUZZTPORT_CLEARING_DOMAIN`)
      - traefik.http.services.clearing.loadbalancer.server.port=9999

  connector:
    labels:
      - traefik.enable=true
      # management api
      - traefik.http.routers.connector-management-http.rule=Host(`$TRUZZTPORT_CONNECTOR_DOMAIN`) && PathPrefix(`/api/v1/management`)
      - traefik.http.routers.connector-management-http.service=connector-management
      - traefik.http.services.connector-management.loadbalancer.server.port=13004

      # ids api
      - traefik.http.routers.connector-ids-http.rule=Host(`$TRUZZTPORT_CONNECTOR_DOMAIN`) && PathPrefix(`//api/v1/ids`)
      - traefik.http.routers.connector-ids-http.service=connector-ids
      - traefik.http.services.connector-ids.loadbalancer.server.port=13003
      - traefik.http.middlewares.example.stripprefix.prefixes=/
      - traefik.http.routers.connector-ids-http.middlewares=example

      # data api
      - traefik.http.routers.connector-data-http.rule=Host(`$TRUZZTPORT_CONNECTOR_DOMAIN`) && PathPrefix(`/api/v1/data`)
      - traefik.http.routers.connector-data-http.service=connector-data
      - traefik.http.services.connector-data.loadbalancer.server.port=13002

      # api
      - traefik.http.routers.connector-api-http.rule=Host(`$TRUZZTPORT_CONNECTOR_DOMAIN`) && PathPrefix(`/api`)
      - traefik.http.routers.connector-api-http.service=connector-api
      - traefik.http.services.connector-api.loadbalancer.server.port=13001
