version: "3.8"

services:
  broker:
    image: ghcr.io/truzzt/mds-broker-core:5.0.3
    environment:
      - SPARQL_ENDPOINT=http://fuseki:3030/connectorData
      - ELASTICSEARCH_HOSTNAME=elastic
      - SHACL_VALIDATION=true
      - DAPS_VALIDATE_INCOMING=false
      - IDENTITY_JAVAKEYSTORE=/etc/cert/keystore.jks
      - COMPONENT_URI=https://broker.$TRUZZTPORT_ENV_SLUG.$TRUZZTPORT_BASE_DOMAIN
      - COMPONENT_CATALOGURI=https://broker.$TRUZZTPORT_ENV_SLUG.$TRUZZTPORT_BASE_DOMAIN/catalog/
      - DAPS_URL=hhttps://daps.$TRUZZTPORT_ENV_SLUG.$TRUZZTPORT_BASE_DOMAIN/token
    depends_on:
      - elastic
      - fuseki
    volumes:
      - ../data/$TRUZZTPORT_ENV_SLUG/broker/:/etc/cert/

  fuseki:
    image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker-open/fuseki
    volumes:
      - ../data/$TRUZZTPORT_ENV_SLUG/fuseki:/fuseki

  elastic:
    image: elasticsearch:7.16.2
    environment:
      - http.port=9200
      - discovery.type=single-node
    volumes:      
      - ../data/$TRUZZTPORT_ENV_SLUG/elastic:/usr/share/elasticsearch/data

  mongo:
    image: mongo:latest
    volumes:
      - ../data/$TRUZZTPORT_ENV_SLUG/mongo:/data/db

  daps:
    image: ghcr.io/fraunhofer-aisec/omejdn-server:1.7.1
    environment:
      - OMEJDN_OPENID=true
      - OMEJDN_ACCEPT_AUDIENCE=idsc:IDS_CONNECTORS_ALL
      - OMEJDN_DEFAULT_AUDIENCE=idsc:IDS_CONNECTORS_ALL
      - OMEJDN_ADMIN=${TRUZZTPORT_ADMIN_USERNAME}:${TRUZZTPORT_ADMIN_PASSWORD}
    volumes:
      - ../data/$TRUZZTPORT_ENV_SLUG/daps/config/:/opt/config/
      - ../data/$TRUZZTPORT_ENV_SLUG/daps/keys:/opt/keys/
